---
settings:
  port: '8080'
  ip: '0.0.0.0'
  daprHost: '0.0.0.0'
  daprPort: '3500'
  server: true
  http2: false
  auth: 'NoAuth'
  cors: true
  json: true
  urlencoded: false
  compression: true
  beforeHooks:
    - 'origin' #set origin header
    - 'requestip' #req.clientIp
    - 'remove-x-powered-by'
    - 'LogRequest'
  afterHooks:
    - 'LogResponse'
  logRequest: info
  logRequestParams: debug
  logResponse: info
  logResponseData:
  log4XXResponses: false
  logRouteRegistration: info
  httpServerTimeout:
  optimizeOrder: true
  rootCallOptions:
  debounceTime: 500
routes: []
